# Generated by Django 5.1.2 on 2024-11-10 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatteryStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('voltage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='CurrentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('current_mA', models.DecimalField(decimal_places=2, max_digits=6)),
                ('remaining_time', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='SensorData',
        ),
        migrations.AddIndex(
            model_name='batterystatus',
            index=models.Index(fields=['timestamp'], name='sensores_ba_timesta_77fccb_idx'),
        ),
        migrations.AddIndex(
            model_name='currentdata',
            index=models.Index(fields=['timestamp'], name='sensores_cu_timesta_c3ee26_idx'),
        ),
    ]
